name: Push

on:
  push:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read
  # Add write permissions if you plan to store binaries in the repository (e.g., releases)
  # issues: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      # Save the built binaries as an artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: path/to/your/binaries

  lint:
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fake Lint Process
        run: echo "Linting step would go here"

  test:
    needs: [build, lint]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Test Environment
        run: echo "Setup test environment here"

      - name: Run Tests
        run: echo "Run tests here"
